on: [push, repository_dispatch]

jobs:
  bundle-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          version: 2.6.x

      - name: Add Gemfile
        run: |
          cat > Gemfile << EOM
          source "https://rubygems.pkg.github.com/melsorg" do
            gem "awesome_gem", "0.0.0"
          end
          EOM
      - name: Add main.rb
        run: |
          cat > main.rb << EOM
          puts 'hello!'
          EOM
      - name: Authenticate using Bundler
        run: bundle config https://rubygems.pkg.github.com/melsorg token:${{ github.token }}

      - name: Install using Bundler
        run: bundle install

      - name: Run using bundle exec
        run: bundle exec ruby main.rb

  gem-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          version: 2.6.x

      - name: Add ~/.gemrc
        run: |
          cat > ~/.gemrc << EOM
          ---
          :backtrace: false
          :bulk_threshold: 1000
          :sources:
          - https://rubygems.org/
          - https://token:${{ github.token }}@rubygems.pkg.github.com/melsorg/
          :update_sources: true
          :verbose: true  
          EOM
      - name: Install Gem
        run: gem install awesome_gem --version "0.0.0"

      - name: Add main.rb
        run: |
          cat > main.rb << EOM
          puts 'hello!'
          EOM
      - name: Run using ruby
        run: ruby main.rb
